SELECT IP.PARTTAKER_CODE, IP.PARTTAKER_NAME, IP.PARENT_CODE,
(SELECT PARTTAKER_NAME FROM INS_PARTTAKER WHERE PARTTAKER_CODE = IP.PARENT_CODE)PARENT_NAME
FROM INS_PARTTAKER IP
WHERE IP.CATEGORY_PARTTAKER_CODE = '08'
AND IP.ACTIVE = 'Y'
AND IP.PARTTAKER_CODE IN 
(
SELECT IA.CLIENT_CODE FROM INS_ASSORTED IA, INS_POLICY_TYPES IPT
WHERE IA.POLICY_TYPE_CODE = IPT.POLICY_TYPE_CODE
AND   IPT.CLASS_CODE IN ('04','05')
AND IA.PERIOD_TO_DATE >=SYSDATE
)