-- CLOSING STATUS --
SELECT IPC.CLASS_NAME,IA.DOCUMENT_CODE,IDP.DOCUMENT_NAME,COUNT(IA.DOCUMENT_CODE)CNT_PENDING,
SUM(FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'GROSS')*1)GROSS,
SUM(FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'NET')*1)NET
FROM INS_ASSORTED IA, INS_POLICY_TYPES IPT,
INS_POLICY_CLASS IPC,INS_DOCUMENT_TYPE IDP
WHERE IA.POLICY_TYPE_CODE = IPT.POLICY_TYPE_CODE
AND IPT.CLASS_CODE = IPC.CLASS_CODE
AND IA.DOCUMENT_CODE = IDP.DOCUMENT_CODE
AND IA.DOCUMENT_CODE IN('04','05','06','07')
AND TRUNC(IA.Issue_Date) BETWEEN '01-July-2024' AND '31-July-2024'
--and ia.is_valid = 'Y'
AND IPT.POLICY_TYPE_CODE <> '77'
AND IA.SUP_BY IS NOT NULL
AND IA.SUP_DATE IS NOT NULL
AND IA.SEQ_NO IS NOT NULL
GROUP BY IPC.CLASS_NAME,IA.DOCUMENT_CODE,IDP.DOCUMENT_NAME;




