-- CONTRIBUTION 0 --
SELECT * FROM INS_ASSORTED IA 
WHERE IA.ASSORTED_STRING LIKE '%26480-08-2024%'
AND IA.POLICY_TYPE_CODE = '76' for update


-- IF STATUS FLAG A THEN ANNUAL RATE OR IF STATUS FLAG R THEN PUT PREVIOUS RATE INTO ANNUAL RATE
  SELECT *  FROM INS_HEALTH_EMPLOYEE_INFO IHEI
  WHERE IHEI.ASSORTED_CODE IN('050000775640')
  AND (IHEI.EMP_CODE = IHEI.ADDITION_EMP_CODE OR IHEI.EMP_CODE = IHEI.CHANGE_EMP_CODE)
  AND NVL(IHEI.RELATION, 'E') ='E' for update
AND IHEI.STATUS_FLAG = 'A'

FOR UPDATE
--WHERE IHEI.HEALTH_ID = '678965' FOR UPDATE;


-- 0 IN TABLE --
SELECT * FROM INS_HEALTH_EMP_RATE_TABLE IHI
--SET IHI.ANNUAL_RATE = '0'
WHERE IHI.EMP_CODE IN(
'58016707'
)
FOR UPDATE;

--RUN PROC_HEALTH_LIFE_UPD

select * from ins_health_plan ik
where ik.assorted_code = '040000149660'

SELECT * FROM INS_ASSORTED 
WHERE POLICY_CODE = '040000149660'

select * from ins_hq_room_limit
