--Daily Fahad --
select 'MOTOR', SUM(TXN_AMOUNT) 
FROM PLS_TRANSACTION_DETAILS
WHERE IS_ACTIVE='Y' AND SUB_PROCESS_ID =105
UNION ALL
select 'HEALTH', SUM(TXN_AMOUNT) 
FROM PLS_HEALTH_TRANSACTIONS_DETAIL
WHERE IS_ACTIVE='Y' AND SUB_PROCESS_ID =205
UNION ALL
select 'NON MOTOR', SUM(TXN_AMOUNT) 
FROM PLS_NM_TRANSACTIONS_DETAIL
WHERE IS_ACTIVE='Y' AND SUB_PROCESS_ID IN (305,405,505,605)




