-- PAK SUZUKI ISSUE --
SELECT func_assorted_string(IA.ASSORTED_CODE)POLICY,
FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'GROSS')*1 GROSS,
FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'FIF')*1 FIF,
FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'FED')*1 FED,
FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'STAMPDUTY')*1 SD,
FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'NET')*1 NET, IA.*
FROM INS_ASSORTED IA
WHERE IA.ENT_BY LIKE '%3100%'
AND IA.DOCUMENT_CODE = '04'
AND IA.IS_VALID = 'Y'
AND TRUNC(IA.ENT_DATE) BETWEEN '01-Mar-2024' AND '29-Mar-2024'
AND IA.SUP_BY IS NULL
AND IA.SUP_DATE IS NULL
AND IA.CUSTODIAN IS NOT NULL
AND IA.ASSORTED_STRING IS NULL
ORDER BY 1 ASC
