-- Pak Suzuki Data from inspection to till date only policies --
SELECT func_assorted_string(IA.ASSORTED_CODE)POLICY,
FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'GROSS')*1 GROSS,
FUNC_GET_AMOUNT_BY_TYPE(IA.ASSORTED_CODE,'NET')*1 NET,(SELECT PARTTAKER_NAME 
FROM INS_PARTTAKER WHERE PARTTAKER_CODE = IA.ENT_BY)USER_NAME,
IA.ISSUE_DATE, IA.PERIOD_FROM, IA.PERIOD_TO_DATE
FROM INS_ASSORTED IA
WHERE IA.ENT_BY like '%31%'
AND IA.DOCUMENT_CODE = '04'
AND IA.IS_VALID = 'Y'
AND Ia.Policy_Type_Code = '02'
AND TRUNC(IA.ENT_DATE) BETWEEN '01-Feb-2023' AND '04-Sep-2025'
AND IA.SUP_BY IS NOT NULL
AND IA.SUP_DATE IS NOT NULL
--AND IA.CUSTODIAN IS NOT NULL
AND IA.ASSORTED_STRING IS Not NULL
ORDER BY 1 ASC
