-- Vehicle Code List --
SELECT V.VEHICLE_CODE,MM.MAKE_NAME,V.VEHICLE_NAME,ICC.CUBIC_HORSE_TITLE,
MVC.VEHICLE_CLASSIFICATION_CODE,MVC.CLASSIFICATION_NAME, MM.MAKE_NAME || ' ' || V.VEHICLE_NAME AS COMPLETE_NAME
FROM MT_VEHICLES V, MT_MAKES MM, MT_VEHICLES_CLASSIFICATIONS MVC, INS_CUBIC_CAPACITIES ICC
WHERE V.MAKE_CODE = MM.MAKE_CODE
AND V.VEHICLE_CLASSIFICATION_CODE = MVC.VEHICLE_CLASSIFICATION_CODE
AND v.cubic_horse_code = ICC.CUBIC_HORSE_CODE


-- Color code List --
select ic.color_code, ic.color_name from ins_colors ic;



