-- ALL CONTRIBUTION --
SELECT * FROM SY_USERS SY 
WHERE SY.USER_CD like(
'%AMINAHMED%'
)
FOR UPDATE;

SELECT * FROM SY_USER_CLIENTS SYC
WHERE SYC.USER_CD = '08818983'
FOR UPDATE;

040000180506




SELECT * FROM INS_ASSORTED IA 
--WHERE IA.CLIENT_CODE = '08801385'
WHERE IA.ASSORTED_STRING LIKE '%3269-08-2024%' --OR IA.ASSORTED_STRING LIKE '%3253-07-2024%'
AND TRUNC(IA.ENT_DATE) <= TRUNC(SYSDATE)
AND IA.DOCUMENT_CODE = '04'
AND IA.POLICY_TYPE_CODE = '76';

--CHECK PARTTAKER NAME --
SELECT * FROM INS_PARTTAKER IP 
WHERE IP.PARTTAKER_CODE = '08818983'
AND IP.CATEGORY_PARTTAKER_CODE = '08'

SELECT * FROM INS_CUBIC_CAPACITIES IPC

SELECT V.VEHICLE_CODE,IM.MAKE_NAME,V.VEHICLE_NAME ,IPX.CUBIC_HORSE_TITLE,VCZ.VEHICLE_CLASSIFICATION_CODE,
VCZ.CLASSIFICATION_NAME
FROM INS_CUBIC_CAPACITIES IPX, MT_VEHICLES V, MT_MAKES IM, MT_VEHICLES_CLASSIFICATIONS VCZ
WHERE V.CUBIC_HORSE_CODE = IPX.CUBIC_HORSE_CODE
AND V.MAKE_CODE = IM.MAKE_CODE
AND V.VEHICLE_CLASSIFICATION_CODE = VCZ.VEHICLE_CLASSIFICATION_CODE
--ORDER BY TO_NUMBER(VD.VEHICLE_SEQ_NO) ASC

SELECT * FROM MT_VEHICLES_CLASSIFICATIONS


select * from ins_vessel iv
--where iv.vessel_name like '%X-PRESS PHOENIX%'
for update
  
SELECT * FROM INS_ASSORTED 
WHERE ASSORTED_STRING LIKE '%3047-02-2024%'
AND DOCUMENT_CODE = '04'
AND TRUNC(ENT_DATE) <= TRUNC(SYSDATE)
AND POLICY_TYPE_CODE = '76'

SELECT * FROM INS_PARTTAKER
--WHERE PARTTAKER_NAME LIKE '%KIA LUCKY MOTORS TOWNSHIP LAHORE%'
WHERE PARTTAKER_CODE = '08818695'
AND CATEGORY_PARTTAKER_CODE = '08' FOR UPDATE

POLICY = 08815968
PROVIDED = 08815968
